<?php

namespace Louvre\TicketingBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByBookingDateOfVisit($date) {
        return $this->createQueryBuilder('booking')
            ->where('booking.dateOfVisit = :date')
            ->setParameter('date', $date->format('Y-m-d'))
            ->getQuery()
            ->execute();

    }



    public function getNumberOfTicketsForADate ($date) {
        return $this->createQueryBuilder('booking')
            ->select('SUM(booking.numberOfTickets) AS totalTickets')
            ->where('booking.dateOfVisit =:date')
            ->setParameter('date', $date->format('Y-m-d'))
            ->getQuery();

    }
}
