<?php

namespace Louvre\TicketingBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends \Doctrine\ORM\EntityRepository
{

    // get the number of tickets sold for a date
    public function getNumberOfTicketsForADate ($date) {

        return $this->createQueryBuilder('booking')
            ->select('SUM(booking.numberOfTickets) AS totalTickets')
            ->where('booking.dateOfVisit =:date')
            ->setParameter('date', $date)
            ->getQuery()
            ->getSingleScalarResult();

    }

    // calculate and get the sum of tickets sold for all booking days
    public function findTicketsAllDays() {
        return $this->createQueryBuilder('booking')
            ->select('booking.dateOfVisit')
            ->addSelect('SUM(booking.numberOfTickets) AS ticketsSum')
            ->groupBy('booking.dateOfVisit')
            ->getQuery()->getArrayResult();
    }




}
