louvre_ticketing_homepage:
    path:     /
    defaults: { _controller: LouvreTicketingBundle:HomePage:index }

louvre_ticketing_bookingpage:
    path:     /booking
    defaults: { _controller: LouvreTicketingBundle:HomePage:booking }