louvre_ticketing_homepage:
    path:     /
    defaults: { _controller: LouvreTicketingBundle:HomePage:index }


louvre_ticketing_bookingsteponepage:
    path:     /booking-step-one
    defaults: { _controller: LouvreTicketingBundle:BookingPage:bookingstepone }

louvre_ticketing_bookingsteptwopage:
    path:     /booking-step-two/{reservationCode}
    defaults: { _controller: LouvreTicketingBundle:BookingPage:bookingsteptwo }

louvre_ticketing_bookingstepthreepage:
    path:     /booking-step-three/{reservationCode}
    defaults: { _controller: LouvreTicketingBundle:BookingPage:bookingstepthree }

louvre_ticketing_bookingstepforpage:
    path:     /booking-step-for/{reservationCode}
    defaults: { _controller: LouvreTicketingBundle:BookingPage:bookingstepfor }