services:
#    louvre_ticketing.example:
#        class: Louvre\TicketingBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    Louvre_Ticketing_Bundle.bookingUtilities:
        class: Louvre\TicketingBundle\Service\BookingUtilities
        arguments: ["@doctrine"]

    Louvre_Ticketing_Bundle.bookingType:
        class: Louvre\TicketingBundle\Form\BookingType
        arguments: ["@Louvre_Ticketing_Bundle.bookingUtilities"]
        tags:
              - { name: form.type }

    Louvre_Ticketing_Bundle.daysImpossibleToBook:
        class: Louvre\TicketingBundle\Validator\Constraints\daysImpossibleToBookValidator
        arguments: ["@Louvre_Ticketing_Bundle.bookingUtilities"]
        tags:
              - { name: validator.constraint_validator }
