services:
#    louvre_ticketing.example:
#        class: Louvre\TicketingBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    Louvre_Ticketing_Bundle.bookingUtilities:
        class: Louvre\TicketingBundle\Services\BookingUtilities